In [1]:
import tensorflow as tf
a = tf.constant(r'Hello World python - via jupyter!')
s = tf.Session()
print(s.run(a))

b'Hello World python - via jupyter!'


In [2]:
import tensorflow as tf
a = tf.constant(r'Hello World !')
s = tf.Session()
print(s.run(a))

b'Hello World !'


In [3]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [5]:
from scipy import sparse

eye = np.eye(4)
print ("numPy array: \n {}" . format(eye))
sparse_matrix = sparse.csr_matrix(eye)
print ("\n Scipy sparse CSR matrix: \n{}".format(sparse_matrix))

numPy array: 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 Scipy sparse CSR matrix: 
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
